export type FinalDataType = {
  theme: string,
  title: string,
  point: string,
  reference: string,
  atribuition: string,
  cod_document: string,
  Angola_participation: string,
  decision: string,
  summary: string,
  create_at: string,
  meeting_number: string,
  comment?: string,
  votoscontra?: string,
  votosfavor?: string,
  votosemabstencao?: string,
  author: string,
  tendencies?: string,
}