import { ReactNode } from "react";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import { ModalContextProvider } from "@/app/contexts/modalContext";
import { VotationContextProvider } from "@/app/hooks/useVotation";
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MED-Relatório",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
}

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={poppins.className}>
        <body className="w-screen h-screen bg-shape-100 antialiased">
          <ModalContextProvider>
            <VotationContextProvider>
              {children}
            </VotationContextProvider>
          </ModalContextProvider>
        </body>
    </html>
  );
}
