import { ReactNode } from "react";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import { ModalContextProvider } from "@/app/contexts/modalContext";
import { VotationContextProvider } from "@/app/hooks/useVotation";
import { FormDataProvider } from "@/app/hooks/useFormData";
import { Theme } from "@radix-ui/themes"
import '@radix-ui/themes/styles.css';
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400'],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: "MED-Relatório",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png',
  },
}

export default function RootLayout({ children }: {
  children: ReactNode, types: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`w-screen h-screen bg-shape-100 antialiased ${poppins.variable}`}>
        <FormDataProvider>
          <ModalContextProvider>
            <VotationContextProvider>
              <Theme>
                {children}
              </Theme>
            </VotationContextProvider>
          </ModalContextProvider>
        </FormDataProvider>
      </body>
    </html>
  );
}
